/**
 * Provider-neutral file storage seam (issue #16).
 *
 * This module is the boundary between SARbase domain code and any object
 * storage backend (local filesystem, S3-compatible object store). Domain
 * records persist only `storageProvider` + `storageKey`; provider SDK
 * objects, URLs, and raw error text never cross this boundary.
 *
 * PRODUCT BOUNDARY: this is documentary storage infrastructure only.
 * Files are untrusted content — SARbase stores, serves, and audits them
 * as records; nothing here inspects file contents or infers operational
 * conclusions from them.
 *
 * Storage keys are opaque identifiers generated by the domain layer
 * (e.g. `organizations/<orgId>/attachments/<uuid>`). Providers must never
 * derive addressing from filenames, member names, or record titles.
 *
 * Adding a provider later: implement `FileStorageProvider`, register it
 * in `resolve.ts` and extend `StorageEnvironment` in `src/lib/env.ts` —
 * the domain layer (`src/lib/domain/attachments.ts`) does not change.
 */

/** Normalized provider failure classification. */
export type StorageErrorCode =
  | "config_missing"
  | "object_not_found"
  | "provider_unavailable"
  | "provider_error";

/**
 * Storage failure with a provider-independent `code` and a safe,
 * operator-facing `message`. Raw provider error text (which may echo
 * credentials, endpoints, request IDs, or bucket paths) is retained in
 * `cause` for server-side diagnostics and must never be rendered or
 * returned to clients.
 */
export class StorageError extends Error {
  readonly code: StorageErrorCode;
  override readonly cause: unknown;

  constructor(code: StorageErrorCode, message: string, cause?: unknown) {
    super(message);
    this.name = "StorageError";
    this.code = code;
    this.cause = cause;
  }
}

/** Thrown when provider configuration is missing or inconsistent. */
export class StorageConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "StorageConfigError";
  }
}

/** Streamed object body returned by `openRead`. */
export interface StorageObjectStream {
  /** Web ReadableStream of the object's bytes — never the whole body. */
  stream: ReadableStream<Uint8Array>;
  sizeBytes: number;
}

export interface StorageObjectStat {
  sizeBytes: number;
  contentType: string | null;
}

export interface FileStorageProvider {
  /**
   * Stable identifier persisted on `Attachment.storageProvider`
   * ("local", "s3"). Never a URL or provider-specific term.
   */
  readonly providerName: string;

  /**
   * Store `body` under `key`. Callers must provide the complete byte
   * sequence (uploads are size-capped well below memory pressure). The
   * provider owns durability semantics; a resolved promise means the
   * object is stored.
   */
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;

  /**
   * Open the object for streaming reads. Throws StorageError
   * `object_not_found` when the key does not exist.
   */
  openRead(key: string): Promise<StorageObjectStream>;

  /**
   * Object metadata without bytes. Returns null when the object does
   * not exist.
   */
  head(key: string): Promise<StorageObjectStat | null>;

  /**
   * Delete the object. Deleting a non-existent key is a no-op success —
   * idempotent deletion keeps repeated delete actions honest.
   */
  delete(key: string): Promise<void>;
}
